language: java
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key.
  - secure: O_cda5pWDBAP-O3_0nG5RQ
addons:
  coverity_scan:
    project:
      name: OpenGrok/OpenGrok
      description: Build submitted via Travis CI
      branch_pattern: coverity_scan
      build_command: ./mvnw -DskipTests=true -Dmaven.javadoc.skip=false -B -V compile
  sonarcloud:
    organization: opengrok
    token:
      secure: ayjmifQPQgKt/ICGfKtLpa8LwBAXZlxKwaPyjvXDRHyf3lbXGKkOCspH/wSoersoV4ZLt5UfSGKeFh1MS0IXAwUOcPTcV3/DUmycJjxZ5z9KjgGKsu0Spo1xZWioS+p1bzN6cJcNlwihE97idLhVSvDProf6L+pn0dqw8Lfz2k0=
jobs:
  include:
  - stage: test
    name: Linux + OpenJDK 8
    os: linux
    dist: xenial
    sudo: required
    jdk: openjdk8
    install: true
    script: dev/main
    before_install: dev/before_install
    before_script: dev/before
  - stage: test
    name: Linux + Oracle JDK 11
    os: linux
    dist: xenial
    sudo: required
    jdk: openjdk11
    install: true
    script: dev/main
    before_install: dev/before_install
    before_script: dev/before
  - stage: test
    name: macOS + Oracle JDK 8
    os: osx
    osx_image: xcode8.3
    install: true
    script: dev/main
    before_install: dev/before_install
    before_script: dev/before
  - stage: deploy
    name: Github Release
    dist: xenial
    jdk: openjdk8
    if: repo = "oracle/opengrok" AND tag IS present
    before_install: dev/before_install
    install: true
    script: dev/pre-deploy.sh
    deploy:
    - provider: releases
      name: "$TRAVIS_TAG"
      prerelease: true
      api_key:
        secure: bCywC9GdBIzLvLG3cgM9SgOAdMRQchmqEyKQZtIfK4iNzH3GjZwLMH91Oha0X3XU/n+nxGKw2E9qpYRzWlcbxHXqIgjFTt+hkt7zAldjjyWJnOcAYqdUDfsH3NqNQBqMBg8q7Bjc0LVS6PfpTpZliZISrL6KSyDprRg7C0S+HAk=
      file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
      skip_cleanup: true
      on:
        condition: "$TRAVIS_TAG =~ rc[0-9]+$"
        all_branches: true
    - provider: releases
      name: "$TRAVIS_TAG"
      api_key:
        secure: bCywC9GdBIzLvLG3cgM9SgOAdMRQchmqEyKQZtIfK4iNzH3GjZwLMH91Oha0X3XU/n+nxGKw2E9qpYRzWlcbxHXqIgjFTt+hkt7zAldjjyWJnOcAYqdUDfsH3NqNQBqMBg8q7Bjc0LVS6PfpTpZliZISrL6KSyDprRg7C0S+HAk=
      file: distribution/target/opengrok-$TRAVIS_TAG.tar.gz
      skip_cleanup: true
      on:
        condition: "$TRAVIS_TAG =~ ^[0-9\\.]+$"
        all_branches: true
  - stage: docker
    name: Docker image build
    dist: xenial
    jdk: openjdk8
    install: true
    services:
    - docker
    before_install: dev/before_install
    before_script: ./mvnw -DskipTests=true -Dmaven.javadoc.skip=true -B -V package
    script: dev/docker.sh
  - stage: javadoc
    name: Upload javadocs to Github pages
    os: linux
    dist: xenial
    jdk: openjdk8
    script: dev/javadoc.sh
    install: true
    if: repo = "oracle/opengrok" AND tag IS NOT present
