version: '{build}'
skip_tags: true
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      PYTHON: C:\Python35
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
  # Prepend Java entry, remove Ruby entry (C:\Ruby193\bin;) from PATH
  - cmd: SET PATH=%JAVA_HOME%\bin;%PYTHON%;%PATH:C:\Ruby193\bin;=%;
  - cmd: mvnw.cmd --version
  - cmd: java -version
  - cmd: python --version
  - cmd: hg --version
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\uctags" )) {
        Write-Host "Downloading Universal Ctags"
        # Project has not had a versioned release so far, but looks like these nightly builds are retained for at least a year
        # so picked an arbitrary version to use for tests
        (new-object System.Net.WebClient).DownloadFile("https://github.com/universal-ctags/ctags-win32/releases/download/2018-09-29%2Fd0807887/ctags-2018-09-29_d0807887-x86.zip", 'C:\uctags-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\uctags-bin.zip", "C:\uctags")
      }
build_script:
    - mvnw.cmd -B -V -Dorg.opengrok.indexer.analysis.Ctags=c:\uctags\ctags.exe clean verify
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
